### ISSUE TITLE
App not coming in foreground.

### ISSUE THREAD

**Issue by jatinmishra** [stammen/AutoLaunch#1]
The background task is triggering as expected but the app is not coming into foreground. It is just blinking in the task bar, it just do not open i.e its window does not appear. 
Any help would be great, I have been trying a lot to accomplish this but I have only found your repo relevant.

Thanks.

**Comment by stammen** [comment]
I just did a build of the project and ran it. After restarting the computer, the app came to the foreground. Which version of Windows are you using?

**Comment by jatinmishra** [comment]
yes, on restarting the computer the app is coming into foreground but I mentioned that when the background task triggers the launch (on timezone change) 
![image](https://user-images.githubusercontent.com/25502209/53469653-cbc09200-3a84-11e9-94c3-5759d31577df.png)

it opens but it is behind the active window. Like in the attached screenshot.


and I want it to to become the active window on launch. Like following screenshot 

![image](https://user-images.githubusercontent.com/25502209/53470306-3a065400-3a87-11e9-98ac-dc03c17ff589.png)


I am using Windows 10 v1809 build 17763.316

**Comment by stammen** [comment]
Unfortunately this is now how Windows 10 works. There is not much I can do to change this. you can always provide feedback to Windows at https://wpdev.uservoice.com/.

**Comment by jatinmishra** [comment]
That's sad (: but anyways thanks for your help.
I am trying to make my UWP app work as a screensaver (it monitors user's inactivity and launches fullscreen after a time interval) could you please provide your personal suggestion as to how I can accomplish something similar to this. 
I know this is off-topic but any help would be greatly appreciated.
